---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "pinnipeds"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_MM_pup_count.csv?time,mean_growth_rate",
title   = "Female sea lion pup growth rate",
y_label = "Mean growth rate",
skip    = 2,
filter  = NULL,
col_t   = NULL,
col_y   = NULL),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_MM_pup_count.csv?time,mean_weight",
title   = "Female sea lion pup weight index",
y_label = "Mean pup weight",
skip    = 2,
filter  = NULL,
col_t   = NULL,
col_y   = NULL),
error = function(e) e)
```

```{r}
tryCatch(plot_timeseries(
csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_MM_pup_count.csv?time,live_pup_count",
title   = "Sea lion pup count, San Miguel Isl.",
y_label = "Average live pup count",
skip    = 2,
filter  = NULL,
col_t   = NULL,
col_y   = NULL),
error = function(e) e)
```
